### ISSUE TITLE
zookeeper package name has been changed

### ISSUE THREAD

**Issue by mhqdotio** [sansible/zookeeper#38]
When fetching the zookeeper package from the mirror hardcoded zookeeper will fail to download.

Looks like the package is now prefixed with `apache-`

**Comment by vpoyraz** [comment]
@mhqdotio any updates on the PR that was merged into develop? We are currently using this role and realised the same issue.

**Comment by mhqdotio** [comment]
@vpoyraz looks like I closed it when I left the company that was using it. Feel free to use the closed code but not sure whats valid at this point in time!
